runtime: python39

entrypoint: python manage.py runserver 0.0.0.0:$PORT

handlers:
  # Serve static files from the static/ directory
  - url: /static
    static_dir: static/

  # Catch-all handler for the application
  - url: /.*
    script: auto


env_variables:
  DJANGO_SETTINGS_MODULE: "VoiGO.settings"
  SECRET_KEY: "django-insecure-%#tpiy69cdle!8ip83bz%0$s13eis1rli3h(qe_n8&-1m&0*0-"
  APPENGINE_URL: https://intelli-cart.el.r.appspot.com/